name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/email.png
    - assets/icons/lock.png
    - assets/icons/potisk.png
    - assets/icons/home.png
    - assets/exercise_gifs/bench_press.gif
    - assets/exercise_gifs/deadlift.gif
    - assets/exercise_gifs/squat.gif
    - assets/exercise_gifs/tek.gif
    - assets/exercise_gifs/kolesarnjene.gif
    - assets/exercise_gifs/jumping_jacks.gif
    - assets/exercise_gifs/overhead_press.gif
    - assets/exercise_gifs/pull-up.gif
    - assets/exercise_gifs/biceps_curl.gif
    - assets/exercise_gifs/tricep_curl.gif
    - assets/exercise_gifs/rowing.gif
    - assets/exercise_gifs/incline_bench.gif
    - assets/exercise_gifs/buterfly.gif
    - assets/exercise_gifs/fly.gif
    - assets/exercise_gifs/dips.gif
    - assets/exercise_gifs/trap_deadlift.gif
    - assets/exercise_gifs/dumbel_row.gif


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
